<?php echo $this->render('tree/header.phtml'); ?>

<div class="editor">
	<h1>Editor</h1>
	<form action="/tree/add">
		<div class="field">
			<label>Parent</label>
			<select name="parent_id">
				<option value="0">--none--</option>
			<?php foreach($this->nodes as $node):?>
				<option value="<?php echo $node->getId();?>"><?php echo $node->getTitle();?></option>
			<?php endforeach;?>
			</select>
		</div>
		<div class="field">
			<label>Title</label>
			<input name="title" type="text"/>
		</div>
		<button>Add node</button>
	</form>
	<ul>
	<?php foreach($this->nodes as $node):?>
		<li>
			<span class="id"><?php echo $node->getId();?></span>
			<span class="parent"><?php echo $node->getParentId();?></span>
			<span class="title"><?php echo $node->getTitle();?></span>
			<span class="delete"><a href="/tree/remove/node_id/<?php echo $node->getId();?>">&times;</a></span>
		</li>
	<?php endforeach;?>
	<ul>
</div>

<?php echo $this->render('tree/footer.phtml');

